### ISSUE TITLE
Translate Readme.md from English to Chinese

### ISSUE THREAD

**Issue by mzorec** [dotnetcore/FlubuCore#218]
Translate in README.zh-cn.md

**Comment by alexinea** [comment]
I have already started to translate the English version of readme into Chinese.

**Comment by mzorec** [comment]
@alexinea Could you move README.zh-cn.md to lang/chinese folder and rename file to README.md please?

**Comment by alexinea** [comment]
@mzorec ok, I will commit another PR.

**Comment by mzorec** [comment]
Thank you. I've added link in english readme.
