### ISSUE TITLE
Translate docs from English to Chinese

### ISSUE THREAD

**Issue by mzorec** [dotnetcore/FlubuCore#224]

**Comment by alexinea** [comment]
What is the structure of the translated version of the document, and where is it placed in `/docs` folder?

**Comment by mzorec** [comment]
I have added multilanguage support for the docs. Just place docs in the /docs/zh folder.

simply run `mkdocs serve -f mkdocs-zh.yml` to host a local version of the docs. If u haven't worked with mkdocs i can provide short instructions about how to get started with mkdocs.

**Comment by mzorec** [comment]
As English is not my first language it would be great if you could take an eye on mistakes in english documentation and fix them if u see any. 

Any suggestions for improvement are also more than welcome.

**Comment by alexinea** [comment]
#233

**Comment by alexinea** [comment]
Chinese document has been translated #233  @mzorec

**Comment by mzorec** [comment]
Awesome work!

I thought  documentation could be hosted at https://flubucore.dotnetcore.xyz/zh but I am having trouble making it happened. Tabs don't work ok. At the moment Chinese documentation is available at https://flubu-core.github.io/docs-zh/ It would be great if we could use https://flubucore-zh.dotnetcore.xyz/ or something similar until issue is resolved. At the moment I don't have time it seems it's not an easy fix. 

I'll also add link to Chinese documentation in English version of documentation and in Chinese github readme. 

Only navigation is not yet translated @alexinea if you could please translate this [commit](https://github.com/dotnetcore/FlubuCore/commit/e8b3657c76406c566db7f21481c6bc53a90a3234)

**Comment by alexinea** [comment]
Is it necessary to change the value of site_dir of mkdocs.yml?

`site_dir: site/zh` for mkdocs-zh.yml and `site_dir: site/en` for modocs.yml？

**Comment by mzorec** [comment]
Could you come to gitter regarding this issue? It will be faster and we won't spam others.

**Comment by alexinea** [comment]
Roger that

**Comment by alexinea** [comment]
I think maybe we can ask @yang-xiaodong
