### ISSUE TITLE
How to pass values across targets

### ISSUE THREAD

**Issue by yang-xiaodong** [dotnetcore/FlubuCore#257]
Hello @mzorec ,

When I was planning to use Flubu instead of the shell script we currently used, I encountered some problems. I need some help from you~ :)

**1. How to pass parameters or variables across targets?**

When the target needs to get the running result of the previous target, how can it be passed or get it?

**2. How to execute commands gracefully?**

As the following script, we use aws ECR as our docker registry. AWS provides a command to log in to Docker, How can I run it directly?

**Sample:** 

```C#
public partial class BuildScript : DefaultBuildScript
{
    [FromArg("c|configuration")]
    public string Configuration { get; set; }

    public string AwsEcrLoginCommand { get; set; }

    protected override void ConfigureBuildProperties(IBuildPropertiesContext context)
    {
        context.Properties.Set(BuildProps.SolutionFileName, "ConsoleApp.sln");
        context.Properties.Set(BuildProps.BuildConfiguration, string.IsNullOrEmpty(Configuration) ? "Release" : Configuration);
    }

    protected override void ConfigureTargets(ITaskContext context)
    {
        var awsEcrLogin = context.CreateTarget("EcrLogin")
            .Do(x =>
                {
                    //SET VALUE HERE
                    AwsEcrLoginCommand = x.Tasks().RunProgram("aws", null, "ecr", "get-login", "--region", "eu-central-1",
                        "--no-include-email")
                        .CaptureOutput()
                        .GetOutput();
                    //the command output:  docker login -u AWS -p xxx  https://xxxxx.dkr.ecr.eu-central-1.amazonaws.com
                });

        var image = context.CreateTarget("EcrImage")
            .DependsOn(awsEcrLogin)
            .Do(x =>
            {
                context.LogInfo("Aws Login command:" + AwsEcrLoginCommand);

                //run docker login command
                var args = AwsEcrLoginCommand.Split(' ').ToArray();
                var loginTask = context.Tasks().RunProgramTask("docker");
                for (int i = 1; i < args.Length; i++) //index from 1, skip `docker`
                {
                    loginTask.WithArguments(args[i]);
                }
            })
            .AddTask(x => x.DockerTasks().Push("xxx"));
    }
}
```

**Comment by mzorec** [comment]
Could you come to gitter please? It will be faster. I'll add answer later to the issue if someone else have similar question.

**Comment by mzorec** [comment]
**1. How to pass parameters or variables across targets?**

You are doing it correctly with properties. There is also an alternative. You could also store it in flubu session. This option is more viable when you want to pass parameters between tasks. 

sample how to store value to session:
 ```c#
context.Properties.Set("AwsEcrLoginCommand", awsEcrLogin);`
```

sample how to get value from session: 
 ```c#
var awsEcrLogin = context.Properties.Get<string>("AwsEcrLoginCommand");
```

Problem in your sample is that you are not executing RunProgramTask in  `Do ` method. 
When you are using tasks through    `context.Tasks()` you have to call  `Execute` method to execute the task:
 ```c#
context.Tasks().RunProgramTask("docker").WithArguments("arg1", "arg2", "arg3").Execute(context)
``` 


Your sample is fixed below

**Note**: if you are adding task to target through AddTask method Flubu calls Execute() when executing that target so in this scenario you should not call Execute() on that task
 ```c#
    context.CreateTarget("awsSample")
            .AddTask(x => x.RunProgramTask("aws")
                .WithArguments("arg1", "arg2", "arg3"));
```
**2. How to execute commands gracefully??** 

Again you are doing it correctly with RunProgramTask but you are not executing RunProgramTask.  Fixed sample below

```c#
public partial class BuildScript : DefaultBuildScript
{
    [FromArg("c|configuration")]
    public string Configuration { get; set; }

    public string AwsEcrLoginCommand { get; set; }

    protected override void ConfigureBuildProperties(IBuildPropertiesContext context)
    {
        context.Properties.Set(BuildProps.SolutionFileName, "ConsoleApp.sln");
        context.Properties.Set(BuildProps.BuildConfiguration, string.IsNullOrEmpty(Configuration) ? "Release" : Configuration);
    }

    protected override void ConfigureTargets(ITaskContext context)
    {
        var awsEcrLogin = context.CreateTarget("EcrLogin")
            .Do(x =>
                {
              var login = context.CreateTarget("LoginEcr")
                .Do(x =>
                {
                    var task = x.Tasks()
                        .RunProgram("aws", null, "ecr", "get-login", "--region", "eu-central-1", "--no-include-email")
                        .CaptureOutput();

                    task.ExecuteVoid(context);

                    AwsEcrLoginCommand = task.GetOutput();            
                });
                });

        var image = context.CreateTarget("EcrImage")
            .DependsOn(awsEcrLogin)
            .Do(c =>
            {
                context.LogInfo("Aws Login command:" + AwsEcrLoginCommand);

                //run docker login command
                var args = AwsEcrLoginCommand.Split(' ').ToArray();
                var loginTask = c.Tasks().RunProgramTask("docker");
                for (int i = 1; i < args.Length; i++) //index from 1, skip `docker`
                {
                    loginTask.WithArguments(args[i]);
                }
            })
             
            loginTask.Execute(c);
           
             c.Tasks().DockerTasks().Push("xxx")).Execute(c);
    }
}
```

**Comment by yang-xiaodong** [comment]
Got it , Thanks for your quick response

**Comment by mzorec** [comment]
No problem. 

Just maybe some more explanation why you have to call Execute in `Do` and not in `AddTask`

> **Note**: if you are adding task to target through AddTask method Flubu calls Execute() when executing that target so in this scenario you should not call Execute() on that task
>  ```c#
>     context.CreateTarget("awsSample")
>             .AddTask(x => x.RunProgramTask("aws")
>                 .WithArguments("arg1", "arg2", "arg3"));
> ```

In the sample above RunProgramTask is added to target. When target is executed Flubu executes all tasks  that were added  to target by calling task `Execute` method. in this case it executes `RunProgramTask`  

 ```c#
context.CreateTarget("LoginEcr")
                .Do(c =>
                {
                    var task = c.Tasks()
                        .RunProgram("aws", null, "ecr", "get-login", "--region", "eu-central-1", "--no-include-email")
                        .CaptureOutput();

                    task.ExecuteVoid(context);
                }
```
In this sample `Do` actually adds  [DoTask](https://github.com/dotnetcore/FlubuCore/blob/master/src/FlubuCore/Tasks/DoTask.cs) to the target. When target is executed Flubu executes `DoTask`. DoTask in above example invokes Anonymous method which was assigned to Action delegate (first parameter in Do Method). 
Flubu can not execute by itself tasks in the anonymous method you have to call Execute method manually.
