### ISSUE TITLE
Interactive mode: History of executed commands doesn't work

### ISSUE THREAD

**Issue by jinmike90** [dotnetcore/FlubuCore#260]
**Describe the bug**
It appears that from version 4.3.0 history of executed commands in interactive mode  doesn't work anymore.   

**To Reproduce**

Library version: 4.3.7
OS: Windows - Power shell

Type dotnet build or any flubu target in interactive mode and then press up or down arrow. It will not work. 

**Expected behavior**
Previously tiped command should appear when pressing up or down arrow.

**Comment by jinmike90** [comment]
Would you do a PR?

**Comment by jinmike90** [comment]
Would you accept a PR?

**Comment by mzorec** [comment]
PR would be more than welcome :)
