### ISSUE TITLE
Pack FlubuCore script as global tool

### ISSUE THREAD

**Issue by SixGoesNine** [dotnetcore/FlubuCore#263]
Would it be possible to pack FlubuCore script as global tool so my team members could execute Targets of the script anywhere without having the actual script?

**Comment by mzorec** [comment]
Interesting idea. I will look into it. If it is possible it will be available in FlubuCore 5.0

**Comment by mzorec** [comment]
You can create global tool by adding below code into your console application. It can also be used as normal console application ofcourse. Debuging your build script is also easier with console application.

```c#
    public class Program
    {
        public static void Main(string[] args)
        {
            var engine = new FlubuEngine();
            engine.RunScript<MyScript>(args);
        }
    }
```

**Comment by mzorec** [comment]
There has been some questions (issues) about the working folder when running script through console application. Probem is that if there is no .flubu file or root directory explicitly set in build script the working folder  when executing script will be project/bin/{configuration} 

It is explained in the documentation with some more details how to solve this: https://flubucore.dotnetcore.xyz/execute-script-in-console-app-or-pack-as-global-tool/
