### ISSUE TITLE
Target DependenceOf

### ISSUE THREAD

**Issue by jinmike90** [dotnetcore/FlubuCore#269]
**Is your feature request related to a problem?**

I would like to make a reverse target dependecy. On target B I would like to define that target B is dependence of target A. This is becuase I have base class for script where target A is defined and in derived class I have Target B where I would like to define in derived class that Target A depends on Target B.

**Describe the solution you'd like**
```C# 
 protected override void ConfigureTargets(ITaskContext context)
 {
        var b = context.CreateTarget("B")
                .DependenceOf(A);
 }
``` 

**Describe alternatives you've considered**
None that I know.

**Comment by mzorec** [comment]
Will be added in FlubuCore 5.0

**Comment by jinmike90** [comment]
Thank you! Works like a charm :)
