### ISSUE TITLE
Dropping support for .NET Standard 1.6

### ISSUE THREAD

**Issue by huanlin** [dotnetcore/FlubuCore#280]
Not sure if anyone still need support for .NET Standard 1.6.
If none, we may drop them in the near future.
While dropping .NET Standard 1.6, we can remove some conditional `#ifdef` statements.

Impact: there might be some packages still require .NET Standard 1.6, then we'll need to either update those packages (if possible) or find other alternatives.

**Comment by huanlin** [comment]
So I think netcoreapp1.0 and netcoreapp1.1 will be removed as well.

**Comment by mzorec** [comment]
Yes i've mentioned this on gitter. netcoreapp1.0 and netcoreapp1.1 support's up to netstandard 1.6.
