### ISSUE TITLE
Update dependent packages to latest compatible versions.

### ISSUE THREAD

**Issue by huanlin** [dotnetcore/FlubuCore#283]
Some dependent packages are a little bit old and contains deprecated APIs, e.g. [CommandLineUtils](https://github.com/natemcmaster/CommandLineUtils)

So I would like to see them updated to latest versions that are compatible with netstandard2.x, .netcoreapp2.x/3.x, and .net462.

**Comment by huanlin** [comment]
If I get a greenlight to do this. I'll start working on it after issue #280 is accepted and merged.

**Comment by mzorec** [comment]
Yes, sure go for it.
