### ISSUE TITLE
RunProgramTask: new command log(text) while running a program is hard to read on white background.

### ISSUE THREAD

**Issue by SixGoesNine** [dotnetcore/FlubuCore#294]
**Describe the bug**
I really like new logging on RunProgramTask and cyan color is nice on black background but unfortunately it is really hard to read logs when they are displayed on white background (we are using jenkins). Screenshot is available below(in the browser it's even harder to read than on the screenshot.)

**To Reproduce**
1. Execute any of the FlubuCore tasks that executes a command or a program.

**Expected behavior**
A clear and concise description of what you expected to happen:

I would like that logs are nicely visible on black and white background.

**Screenshots**
![image](https://user-images.githubusercontent.com/32750732/79061890-1014ee80-7c95-11ea-8d31-207e0885b37f.png)

**Comment by mzorec** [comment]
I can cofirm that it is hard to read on white background.

@huanlin or @SixGoesNine Would you be willing to do a PR?

**Comment by mzorec** [comment]
Changed color to DarkCyan.. looks good on both backgrounds

**Comment by huanlin** [comment]
Sorry, I was too late when I saw this. Thanks for improving it.
