### ISSUE TITLE
RootDirectory is not set on linux when using .flubu file

### ISSUE THREAD

**Issue by jinmike90** [dotnetcore/FlubuCore#297]
**Describe the bug**
When I have added .flubu file I got the following error in ubuntu 19.04

> ERROR: System.ArgumentException: The path is empty.
Parameter name: path
   at System.IO.Path.GetFullPath(String path)
   at FlubuCore.Scripting.DefaultBuildScript.get_RootDirectory()
   at BuildScript.get_Output() in BuildScript/BuildScript.cs:line 16

**To Reproduce**
1. Using this version of the library: 5.0.4
2. Just access root directory in the build script.

**Expected behavior**
When accessing RootDirectory should not fail.

**Comment by mzorec** [comment]
Fix is already available in 5.1.0-preview1

**Comment by jinmike90** [comment]
Wow thank you for the really quick fix! Works perfectly.
