### ISSUE TITLE
Update Microsoft.Extensions.Logging to version 3.1.3

### ISSUE THREAD

**Issue by huanlin** [dotnetcore/FlubuCore#313]
Current: Microsoft.Extensions.Logging 2.1.1

While updating Microsoft.Extensions.Logging to version 3.1.3, several classes are removed, including `WindowsLogConsole`, `AnsiLogConsole`, `IAnsiSystemConsole`..., etc. We might need to copy some of them into FlubuCore.

Affected projects: FlubuCore and FlubuCore.Tests.

**Comment by huanlin** [comment]
@mzorec , do you want this to be handled in 6.0 or develop branch?

**Comment by mzorec** [comment]
I have merged 6.0 into develop so you can do this on develop branch. Could you come to gitter?
