### ISSUE TITLE
Cannot create a new Git branch with the given name

### ISSUE THREAD

**Issue by ali-tayebi** [dotnetcore/FlubuCore#317]
**Describe the bug**
Cannot pass a new branch name to `NewBranch` from `GitCheckoutTask`
Also, `Checkout` method force passing a branch name which is not really required in this case

**To Reproduce**
Steps to reproduce the behaviour:
1. Using this version of the library '5.1.1'
2. Run this code

```
          context
                .CreateTarget("branch")
                .SetDescription("Create a new branch")
                .AddTask(task => task
                    .GitTasks()
                    .Checkout("")
                    .NewBranch("my_new_branch")
```

3. With no arguments
```
   /usr/local/bin/git  checkout -b

   error: switch `b' requires a value
```

**Expected behaviour**
A new branch named `my_new_branch` should be created 

**Screenshots**
![Screen Shot 2020-04-30 at 5 12 19 pm](https://user-images.githubusercontent.com/4958087/80682394-c1c17580-8b05-11ea-9d68-725535fb3d5b.png)

**Additional context**
Please have a look at [this line](https://github.com/dotnetcore/FlubuCore/blob/develop/src/FlubuCore/Tasks/Git/GitCheckoutTask.cs#L41) of code. It seems the parameter `name` should be passed through.

**Comment by mzorec** [comment]
Thank you for reporting the issue.  Yes problem is that the `name` parameter is not passed through.  Branch name will also be changed to optional parameter.

For now as an alternative you can just write

```
          context
                .CreateTarget("branch")
                .SetDescription("Create a new branch")
                .AddTask(task => task
                    .GitTasks()
                    .Checkout("")
                    .WithArguments("-b", "my_new_branch")
```

**Comment by ali-tayebi** [comment]
@mzorec 
Thanks for the reply and the workaround. It unblocks me for now
