### ISSUE TITLE
FlubuCore WebApi: Connection string platform does not support FileStream.Lock issue on OSX

### ISSUE THREAD

**Issue by mzorec** [dotnetcore/FlubuCore#320]
System.InvalidOperationException: Your platform does not support FileStream.Lock. Please set mode=Exclusive in your connnection string to avoid this error.

When mode is changed to exclusive then when atleast executing tests db file is being locked and cannot write to the file.

Bug is reproducable on: github actions macos build https://github.com/dotnetcore/FlubuCore/runs/687019086

**Comment by huanlin** [comment]
After I update LiteDB to v5 and add `Upgrade=true;Connection=Share` to all LiteDB connection strings, the FileStream.Lock issue seems gone: https://github.com/dotnetcore/FlubuCore/runs/689187381?check_suite_focus=true

However, there are 2 tests failed regarding Logs/log_yyyy-dd-M.db. I inspect that file with LiteDB Studio, and it doesn't contain "logs" collection. Until now, I couldn't solve this mystery myself.

**Comment by mzorec** [comment]
For storing logs into litedb database serilog litedb sink is used.

this is configured in startup
https://github.com/dotnetcore/FlubuCore/blob/65b0e48a3da7a9a0f544cea9e28d12338b48d39d/src/FlubuCore.WebApi/Startup.cs#L79

It looks like currently used version of this sink does not work with LiteDb 5 hence no logs :) I forgot why I didnt use nuget package for this package it is located at  src\packages\SerilogSinksLiTeDb

**Comment by mzorec** [comment]
There is new version available  https://www.nuget.org/packages/Serilog.Sinks.LiteDB so updating this package should fix the issue.

**Comment by huanlin** [comment]
> There is new version available https://www.nuget.org/packages/Serilog.Sinks.LiteDB so updating this package should fix the issue.

Thanks for the tip! Now log db has data, and I don't see FileStream.Lock errors:
https://github.com/dotnetcore/FlubuCore/actions/runs/110045921
