### ISSUE TITLE
Windows service deployment example

### ISSUE THREAD

**Issue by martynasramonas** [dotnetcore/FlubuCore#341]
Hi,
I am not able to find any example or documentation with windows services deployment. Would it be possible to get a small example? Thanks in advance.

**Comment by mzorec** [comment]
Hi,

I have added build and deploy script example: https://github.com/dotnetcore/FlubuCore.Examples/tree/master/WindowsServiceDeployScriptExample

Example deploy script does not create windows service. You have to create it manually. Ofcourse you could also automate this step to.  

If you have any more questions fell free to ask.

**Comment by martynasramonas** [comment]
Great. Thanks a lot.
