### ISSUE TITLE
Is C# 9 supported by FlubuCore 6.1.0?

### ISSUE THREAD

**Issue by azabluda** [dotnetcore/FlubuCore#345]
Just wanted to try some C# 9 features like `record Test(string arg1);` in my Flubu script, but got this error
```
ScriptError:CS0246: The type or namespace name 'record' could not be found (are you missing a using directive or an assembly reference?)
```
Is there any way to enable it?

**Comment by mzorec** [comment]
Roslyn nuget packages had to be updated. Flubu 6.1.1 was released where C# 9 features are now supported.
