### ISSUE TITLE
FlubuCore.Runner - Merge FlubuCore.dll into flubu.exe

### ISSUE THREAD

**Issue by mzorec** [dotnetcore/FlubuCore#5]

**Comment by jenzy** [comment]
This seems like an easy fix - removing the argument `--exclude FlubuCore.dll` in the libz command in TargetMerge in BuildScript.cs. Some care must be taken not to move  FubuCore.dll as it it still needed for the nuget package. Is there any other reason that FlubuCore.dll was excluded?

**Comment by zoroz** [comment]
Yes, the fix is really simple. But FlubuCore.dll was originally excluded because of a bug in libz/VS. Intellisense was not working correctly when packed version was added to the reference list. Will have to re-test if this is resolved now.

**Comment by mzorec** [comment]
Problem is also that u have to load FlubuCore.dll before executing build script. If u inject FlubuCore.dll into build.exe u have to load whole build.exe which is a bit inconvenient. Becasuse we would lode some dlls that are not needed and increase even more startup time. If I remember script execution wasn't even working correctly if we loaded build.exe

**Comment by mzorec** [comment]
won't fix.
